extends Control

const BG := Color("#050712")
const PANEL := Color("#0A0F1D")
const CYAN := Color("#58E7FF")
const PURPLE := Color("#B86CFF")
const PINK := Color("#FF5EC4")
const GOLD := Color("#FFB84D")
const WHITE := Color("#F5F7FF")
const MUTED := Color("#8992B4")

var screen := "home"
var selected_fighter := 0

func _ready() -> void:
	_show("home")

func _show(next: String) -> void:
	screen = next
	for c in get_children():
		c.queue_free()
	await get_tree().process_frame
	_build_background()
	match screen:
		"home": _home()
		"characters": _characters()
		"place": _place()
		"settings": _settings()

func _process(_delta: float) -> void:
	queue_redraw()

func _draw() -> void:
	var s := get_viewport_rect().size
	draw_rect(Rect2(Vector2.ZERO, s), BG)
	draw_circle(Vector2(s.x * 0.15, s.y * 0.2), 270.0, Color(CYAN, 0.035))
	draw_circle(Vector2(s.x * 0.86, s.y * 0.28), 320.0, Color(PURPLE, 0.045))
	draw_circle(Vector2(s.x * 0.58, s.y * 0.90), 360.0, Color(PINK, 0.025))

func _build_background() -> void:
	add_child(_label("✦  HUNTER'S RISE", Vector2(52, 40), Vector2(360, 32), 21, WHITE))
	add_child(_label(_step(), Vector2(54, 72), Vector2(420, 22), 11, CYAN))
	var v := _label("GODOT 4  •  BUILD 1.0", Vector2(1000, 46), Vector2(225, 22), 11, MUTED)
	v.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	add_child(v)

func _step() -> String:
	match screen:
		"home": return "MAIN MENU"
		"characters": return "01 / SELECT CHARACTER"
		"place": return "02 / SELECT PLACE"
		"settings": return "SYSTEM / SETTINGS"
	return ""

func _home() -> void:
	add_child(_label("HUNTER'S\nRISE", Vector2(72, 150), Vector2(570, 140), 82, WHITE))
	add_child(_label("NEON DISTRICT", Vector2(76, 306), Vector2(300, 25), 16, CYAN))
	add_child(_label("Two original fighters. One city. One clean fight flow.\nEverything in this prototype is generated by the Godot project.", Vector2(76, 348), Vector2(500, 64), 15, MUTED))
	var play := _button("PLAY", Vector2(76, 448), Vector2(280, 64), CYAN)
	play.pressed.connect(func(): _show("characters"))
	add_child(play)
	var chars := _button("CHARACTERS", Vector2(76, 528), Vector2(280, 52), PURPLE)
	chars.pressed.connect(func(): _show("characters"))
	add_child(chars)
	var settings := _button("SETTINGS", Vector2(76, 594), Vector2(280, 46), Color("#3D4568"))
	settings.pressed.connect(func(): _show("settings"))
	add_child(settings)

	var card := _card(Vector2(670, 155), Vector2(480, 415))
	add_child(card)
	add_child(_label("2 ORIGINAL 3D FIGHTERS", Vector2(704, 190), Vector2(350, 24), 11, CYAN))
	add_child(_label("REX  +  ZARA", Vector2(704, 224), Vector2(360, 44), 30, WHITE))
	add_child(_label("NEON DISTRICT", Vector2(704, 318), Vector2(320, 38), 26, WHITE))
	add_child(_label("A complete city scene around a dedicated\ncombat platform: skyline, streets, lights,\nbillboards, props and neon accents.", Vector2(704, 364), Vector2(390, 80), 14, MUTED))
	add_child(_label("LOCAL VERSUS  •  60 SECOND ROUND", Vector2(704, 472), Vector2(360, 24), 11, PINK))
	add_child(_label("NO EXTERNAL ASSET PATH REQUIRED", Vector2(704, 510), Vector2(380, 24), 11, GOLD))

func _characters() -> void:
	add_child(_label("SELECT YOUR CHARACTER", Vector2(72, 132), Vector2(640, 50), 38, WHITE))
	add_child(_label("The other fighter becomes Player 02 automatically.", Vector2(74, 184), Vector2(620, 25), 15, MUTED))
	_character_card(Vector2(72, 240), "Rex", "TECHNICAL STRIKER", CYAN, 0)
	_character_card(Vector2(664, 240), "Zara", "PHASE ASSAULT", PINK, 1)
	var back := _button("BACK", Vector2(72, 634), Vector2(150, 44), Color("#3D4568"))
	back.pressed.connect(func(): _show("home"))
	add_child(back)
	var next := _button("PLACE  →", Vector2(918, 624), Vector2(220, 54), CYAN)
	next.pressed.connect(func(): _show("place"))
	add_child(next)

func _character_card(pos: Vector2, fighter: String, role: String, accent: Color, index: int) -> void:
	var root := Control.new()
	root.position = pos
	root.size = Vector2(520, 360)
	root.add_child(_card(Vector2.ZERO, root.size))
	var bar := ColorRect.new()
	bar.size = Vector2(6, root.size.y)
	bar.color = accent
	root.add_child(bar)
	root.add_child(_label("FIGHTER %02d" % (index + 1), Vector2(28, 18), Vector2(180, 20), 11, MUTED))
	root.add_child(_label(fighter.to_upper(), Vector2(28, 46), Vector2(280, 42), 32, WHITE))
	root.add_child(_label(role, Vector2(30, 88), Vector2(280, 22), 12, accent))

	var preview := Panel.new()
	preview.position = Vector2(26, 122)
	preview.size = Vector2(220, 205)
	var ps := StyleBoxFlat.new()
	ps.bg_color = Color(accent.r, accent.g, accent.b, 0.05)
	ps.border_color = Color(accent.r, accent.g, accent.b, 0.32)
	ps.set_border_width_all(1)
	preview.add_theme_stylebox_override("panel", ps)
	root.add_child(preview)
	_add_fighter_preview(preview, index)

	root.add_child(_label("STYLE", Vector2(278, 130), Vector2(80, 18), 10, MUTED))
	root.add_child(_label("SWIFT" if index == 0 else "PHASE", Vector2(278, 151), Vector2(160, 28), 18, WHITE))
	root.add_child(_label("SIGNATURE", Vector2(278, 193), Vector2(110, 18), 10, MUTED))
	root.add_child(_label("RUSH" if index == 0 else "PHASE BURST", Vector2(278, 214), Vector2(190, 28), 17, accent))
	root.add_child(_label("3D MODEL", Vector2(278, 255), Vector2(110, 18), 10, MUTED))
	root.add_child(_label("READY", Vector2(278, 277), Vector2(100, 22), 12, GOLD))

	var select := _button("SELECT", Vector2(366, 308), Vector2(126, 36), accent)
	select.add_theme_font_size_override("font_size", 14)
	select.pressed.connect(func(): selected_fighter = index; _show("characters"))
	root.add_child(select)
	if selected_fighter == index:
		root.add_child(_label("SELECTED", Vector2(28, 333), Vector2(100, 18), 10, accent))
	add_child(root)

func _add_fighter_preview(parent: Control, fighter_index: int) -> void:
	var holder := SubViewportContainer.new()
	holder.position = Vector2(1, 1)
	holder.size = parent.size - Vector2(2, 2)
	holder.mouse_filter = Control.MOUSE_FILTER_IGNORE
	var vp := SubViewport.new()
	vp.size = Vector2i(int(holder.size.x), int(holder.size.y))
	vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	var env := WorldEnvironment.new()
	var e := Environment.new()
	e.background_mode = Environment.BG_COLOR
	e.background_color = Color("#070914")
	e.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	e.ambient_light_color = Color("#A2B9D8")
	e.ambient_light_energy = 0.9
	env.environment = e
	vp.add_child(env)
	var light := OmniLight3D.new()
	light.position = Vector3(-2.0, 3.0, 2.2)
	light.light_color = CYAN if fighter_index == 0 else PINK
	light.light_energy = 8.0
	light.omni_range = 6.0
	vp.add_child(light)
	var cam := Camera3D.new()
	cam.position = Vector3(0, 1.30, 3.45)
	cam.current = true
	cam.look_at(Vector3(0, 1.08, 0), Vector3.UP)
	vp.add_child(cam)
	var fighter := FighterFactory.create_fighter("Rex" if fighter_index == 0 else "Zara", CYAN if fighter_index == 0 else PINK, Color("#6E7CFF") if fighter_index == 0 else GOLD)
	vp.add_child(fighter)
	holder.add_child(vp)
	parent.add_child(holder)

func _place() -> void:
	add_child(_label("SELECT YOUR PLACE", Vector2(72, 132), Vector2(620, 50), 38, WHITE))
	add_child(_label("A whole city surrounds the fight; only the center is the combat zone.", Vector2(74, 184), Vector2(760, 25), 15, MUTED))
	var card := _card(Vector2(72, 238), Vector2(1066, 350))
	add_child(card)
	_add_arena_preview(card)
	add_child(_label("NEON DISTRICT", Vector2(648, 274), Vector2(380, 40), 30, WHITE))
	add_child(_label("CITY / NIGHT / CENTRAL COMBAT DECK", Vector2(650, 318), Vector2(380, 22), 11, CYAN))
	add_child(_label("Skyline, streets, buildings, lamps, billboards,\nprops and neon framing all sit behind the\ncentral fighting platform.", Vector2(650, 356), Vector2(390, 82), 15, MUTED))
	add_child(_label("ARENA READY", Vector2(650, 468), Vector2(180, 22), 12, GOLD))
	var fight := _button("FIGHT  →", Vector2(910, 516), Vector2(190, 54), PINK)
	fight.pressed.connect(_enter_fight)
	add_child(fight)
	var back := _button("← BACK", Vector2(72, 620), Vector2(150, 46), Color("#3D4568"))
	back.pressed.connect(func(): _show("characters"))
	add_child(back)

func _add_arena_preview(parent: Control) -> void:
	var holder := SubViewportContainer.new()
	holder.position = Vector2(20, 28)
	holder.size = Vector2(555, 294)
	holder.mouse_filter = Control.MOUSE_FILTER_IGNORE
	var vp := SubViewport.new()
	vp.size = Vector2i(555, 294)
	vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	var env := WorldEnvironment.new()
	var e := Environment.new()
	e.background_mode = Environment.BG_COLOR
	e.background_color = Color("#02040A")
	e.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	e.ambient_light_color = Color("#94AED5")
	e.ambient_light_energy = 0.85
	e.glow_enabled = true
	e.glow_intensity = 0.65
	env.environment = e
	vp.add_child(env)
	var light := DirectionalLight3D.new()
	light.rotation_degrees = Vector3(-50, -28, 0)
	light.light_energy = 1.1
	light.shadow_enabled = true
	vp.add_child(light)
	var cam := Camera3D.new()
	cam.position = Vector3(16, 11, 16)
	cam.current = true
	cam.look_at(Vector3(0, 2.4, 0), Vector3.UP)
	vp.add_child(cam)
	var arena := ArenaFactory.build(vp)
	arena.scale = Vector3.ONE * 0.65
	holder.add_child(vp)
	parent.add_child(holder)

func _enter_fight() -> void:
	get_tree().set_meta("selected_fighter", selected_fighter)
	get_tree().change_scene_to_file("res://game_combat.tscn")

func _settings() -> void:
	add_child(_label("SETTINGS", Vector2(72, 132), Vector2(400, 50), 38, WHITE))
	add_child(_label("Keyboard controls are fixed for the first playable build.", Vector2(74, 184), Vector2(680, 25), 15, MUTED))
	var card := _card(Vector2(72, 244), Vector2(1066, 286))
	add_child(card)
	add_child(_label("P1", Vector2(28, 30), Vector2(80, 22), 11, MUTED))
	add_child(_label("A/D move   W jump   F/G/H attack   R block   T dash", Vector2(150, 26), Vector2(790, 28), 14, WHITE))
	add_child(_label("P2", Vector2(28, 92), Vector2(80, 22), 11, MUTED))
	add_child(_label("LEFT/RIGHT move   UP jump   J/K/L attack   I block   O dash", Vector2(150, 88), Vector2(820, 28), 14, WHITE))
	add_child(_label("MENU", Vector2(28, 154), Vector2(80, 22), 11, MUTED))
	add_child(_label("ESC returns to Home   ENTER rematches after KO", Vector2(150, 150), Vector2(720, 28), 14, WHITE))
	add_child(_label("ENGINE", Vector2(28, 216), Vector2(80, 22), 11, MUTED))
	add_child(_label("Godot 4.x / GL Compatibility", Vector2(150, 212), Vector2(720, 28), 14, WHITE))
	var back := _button("← HOME", Vector2(72, 584), Vector2(160, 50), CYAN)
	back.pressed.connect(func(): _show("home"))
	add_child(back)

func _card(pos: Vector2, size: Vector2) -> Panel:
	var p := Panel.new()
	p.position = pos
	p.size = size
	var s := StyleBoxFlat.new()
	s.bg_color = PANEL
	s.border_color = Color(0.35, 0.45, 0.75, 0.22)
	s.set_border_width_all(1)
	s.corner_radius_top_left = 14
	s.corner_radius_top_right = 14
	s.corner_radius_bottom_left = 14
	s.corner_radius_bottom_right = 14
	p.add_theme_stylebox_override("panel", s)
	return p

func _label(text_value: String, pos: Vector2, size: Vector2, font_size: int, color: Color) -> Label:
	var l := Label.new()
	l.text = text_value
	l.position = pos
	l.size = size
	l.add_theme_font_size_override("font_size", font_size)
	l.add_theme_color_override("font_color", color)
	return l

func _button(text_value: String, pos: Vector2, size: Vector2, accent: Color) -> Button:
	var b := Button.new()
	b.text = text_value
	b.position = pos
	b.size = size
	b.add_theme_font_size_override("font_size", 17)
	b.add_theme_color_override("font_color", WHITE)
	var n := StyleBoxFlat.new()
	n.bg_color = Color(accent.r, accent.g, accent.b, 0.10)
	n.border_color = Color(accent.r, accent.g, accent.b, 0.50)
	n.set_border_width_all(1)
	n.corner_radius_top_left = 10
	n.corner_radius_top_right = 10
	n.corner_radius_bottom_left = 10
	n.corner_radius_bottom_right = 10
	var h := n.duplicate()
	h.bg_color = Color(accent.r, accent.g, accent.b, 0.23)
	h.border_color = Color(accent.r, accent.g, accent.b, 0.90)
	b.add_theme_stylebox_override("normal", n)
	b.add_theme_stylebox_override("hover", h)
	b.add_theme_stylebox_override("pressed", h)
	return b
